### ISSUE TITLE
The PC can randomly grow a cock at night sometimes.

### ISSUE THREAD

**Issue by ReliableNarrator** [nergantre/nightgamesmod#30]
I only started noticing it when moving the male preference slider to the right, so I assume the opponents are using the drafts on themselves/others and it's affecting the PC somehow.

**Comment by dndw** [comment]
Fixed in my fork. Temporary body modifications were handled properly, but the rare permanent effects were not.

Body#clone would make a deep copy of the replacements, but the permanent effects use Body#add, which places the modifications in the main list instead of the replacements. That method would be called even if the skill were only simulated for the AI, and the effects would then persist even if the skill was not actually picked. The fix is simply to deep-copy Body#bodyParts as well when cloning.
